image: samadhi/frontend-tools

pipelines:
  branches:
      master:
          - step:
              script:
                  - cd client
                  - npm install
                  - grunt publish
                  - s3_website push --site=dist
