image: samadhi/frontend-tools

pipelines:
  branches:
      master:
          - step:
              script:
                  - cd client && grunt publish
                  - cd client && s3_website push --site=dist
