image: samadhi/frontend-tools

pipelines:
  branches:
      master:
          - step:
              script:
                  - cd client
                  - apk add git
                  - gem install compass
                  - npm install
                  - bower install --allow-root
                  - grunt publish
                  - s3_website push --site=dist
